### ISSUE TITLE
Demo account for testing api ?

### ISSUE THREAD

**Issue by PietkaSmig** [Intelecom/Puzzel-Pay#2]
Hi, do you have any demo account to test rest API  ? We would like to test it instead of SFTP api. 

Kind regards - Piotr

**Comment by t2tviking** [comment]
Hi Piotr,

I have forwarded your request to our customer support - on what email address can we contact you?


Kind regards,

Kjetil Johannesen
Intelecom

**Comment by PietkaSmig** [comment]
Hi Kjetil, 

Thank you, piotr.smigielski [at] smalerhuset.com , we just need some user for testing.

Br - Piotr

**Comment by t2tviking** [comment]
Thank you, you'll hear from us shortly!
